# Generated by Django 6.0.3 on 2026-03-05 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='전략명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('minute60', '1시간봉'), ('minute240', '4시간봉'), ('day', '일봉'), ('week', '주봉'), ('month', '월봉')], default='day', max_length=20)),
                ('offset', models.IntegerField(default=0, verbose_name='n봉 전')),
                ('left_indicator', models.CharField(choices=[('MA', '이동평균(MA)'), ('RSI', 'RSI'), ('VAL', '고정값')], default='MA', max_length=10)),
                ('left_param', models.IntegerField(default=5, verbose_name='좌변 기간/값')),
                ('operator', models.CharField(choices=[('gt', '크다 (>)'), ('lt', '작다 (<)')], default='gt', max_length=5)),
                ('right_indicator', models.CharField(choices=[('MA', '이동평균(MA)'), ('RSI', 'RSI'), ('VAL', '고정값')], default='MA', max_length=10)),
                ('right_param', models.IntegerField(default=20, verbose_name='우변 기간/값')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='screener.strategy')),
            ],
        ),
    ]
