# Generated by Django 4.2 on 2026-06-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0004_ha_indicators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='bb_period',
        ),
        migrations.AddField(
            model_name='condition',
            name='offset_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alertsetting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='bb_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='left_param',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='condition',
            name='right_param',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='condition',
            name='timeframe',
            field=models.CharField(choices=[('minute1', '1분봉'), ('minute3', '3분봉'), ('minute5', '5분봉'), ('minute10', '10분봉'), ('minute15', '15분봉'), ('minute30', '30분봉'), ('minute60', '1시간봉'), ('minute240', '4시간봉'), ('day', '일봉'), ('week', '주봉'), ('month', '월봉')], default='day', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
