# Generated by Django 4.2 on 2026-06-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0007_alter_condition_left_indicator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='코인 심볼')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='진입 가격')),
                ('volume', models.FloatField(default=0, verbose_name='거래대금')),
                ('details', models.TextField(blank=True, verbose_name='매칭 상세')),
                ('status', models.CharField(default='new', max_length=20, verbose_name='매칭 상태')),
                ('is_notified', models.BooleanField(default=True, verbose_name='텔레그램 발송 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발송 시각')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='screener.strategy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
