# Generated by Django 4.2 on 2026-06-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0009_alter_condition_left_indicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='capital_pct',
            field=models.IntegerField(default=20, verbose_name='진입 자본 비율 (%)'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='stop_loss',
            field=models.FloatField(default=-8.0, verbose_name='손절 기준 (%)'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='take_profit',
            field=models.FloatField(default=24.0, verbose_name='목표 익절 (%)'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='win_rate',
            field=models.FloatField(default=60.0, verbose_name='승률 (%)'),
        ),
    ]
