# Generated by Django 4.2 on 2026-07-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0010_strategy_capital_pct_strategy_stop_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='offset',
            field=models.IntegerField(default=0, verbose_name='n봉 이내'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='operator',
            field=models.CharField(choices=[('gt', '크다 (>)'), ('lt', '작다 (<)'), ('gte', '이상 (>=)'), ('lte', '이하 (<=)'), ('btw', '사이 (A <= X <= B)'), ('cross_up', '상향 돌파 (Cross Up)'), ('cross_down', '하향 돌파 (Cross Down)'), ('is', '조건 충족')], default='gte', max_length=15),
        ),
    ]
