# Generated by Django 4.2 on 2026-07-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0011_alter_condition_offset_alter_condition_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(db_index=True, max_length=20)),
                ('ticker', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('close_price', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['exchange', 'ticker'], name='screener_ma_exchang_505f69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketdata',
            unique_together={('exchange', 'ticker')},
        ),
    ]
