# Generated by Django 4.2 on 2026-07-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0012_marketdata_marketdata_screener_ma_exchang_505f69_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLCVCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=50)),
                ('timeframe', models.CharField(db_index=True, max_length=50)),
                ('data', models.JSONField(verbose_name='OHLCV JSON Data')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='ohlcvcache',
            index=models.Index(fields=['ticker', 'timeframe'], name='screener_oh_ticker_af1610_idx'),
        ),
        migrations.AddIndex(
            model_name='ohlcvcache',
            index=models.Index(fields=['updated_at'], name='screener_oh_updated_18be72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ohlcvcache',
            unique_together={('ticker', 'timeframe')},
        ),
    ]
