# Generated by Django 4.2.30 on 2026-07-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0017_delete_customalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='추천일')),
                ('coin_ticker', models.CharField(max_length=50, verbose_name='티커')),
                ('coin_name', models.CharField(max_length=100, verbose_name='종목명')),
                ('entry_price', models.FloatField(verbose_name='진입 추천가')),
                ('target_price', models.FloatField(verbose_name='목표가')),
                ('stop_loss', models.FloatField(verbose_name='손절가')),
                ('k_value', models.FloatField(default=0.5, verbose_name='적용된 K값')),
                ('reason', models.TextField(verbose_name='추천 이유')),
                ('status', models.CharField(choices=[('pending', '진입대기'), ('active', '매수완료'), ('success', '목표달성'), ('failed', '손절이탈'), ('closed', '마감')], default='pending', max_length=20, verbose_name='상태')),
                ('result_pct', models.FloatField(blank=True, null=True, verbose_name='최종 수익률(%)')),
                ('highest_price', models.FloatField(blank=True, null=True, verbose_name='진입 후 최고가')),
                ('lowest_price', models.FloatField(blank=True, null=True, verbose_name='진입 후 최저가')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'coin_ticker'],
                'unique_together': {('date', 'coin_ticker')},
            },
        ),
    ]
