# Generated by Django 4.2.30 on 2026-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0018_dailyrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecommendation',
            name='status',
            field=models.CharField(choices=[('pending', '진입대기'), ('active', '매수완료'), ('success', '목표달성'), ('failed', '손절이탈'), ('closed', '마감'), ('skipped', '단타휴식')], default='pending', max_length=20, verbose_name='상태'),
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=300, verbose_name='경로')),
                ('method', models.CharField(default='GET', max_length=8, verbose_name='메서드')),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('referer', models.CharField(blank=True, max_length=300, verbose_name='Referer')),
                ('status_code', models.IntegerField(default=200, verbose_name='응답 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='방문 시각')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='screener_vi_created_90d435_idx'), models.Index(fields=['ip'], name='screener_vi_ip_9236be_idx')],
            },
        ),
    ]
