# Generated by Django 4.2.30 on 2026-08-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0019_alter_dailyrecommendation_status_visitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='owner_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='소유자 세션키'),
        ),
    ]
