# Generated by Django 4.2.30 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0023_dailyrecommendation_swing_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecommendation',
            name='last_checked_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='마지막 시세 확인 시각',
            ),
        ),
    ]
