# Generated by Django 4.2.30 on 2026-09-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0034_dailyrecommendation_strategy_version_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntradayObservation',
        ),
        migrations.AlterField(
            model_name='dailyrecommendation',
            name='trade_type',
            field=models.CharField(choices=[('danta', '단타'), ('swing', '스윙')], db_index=True, default='swing', max_length=10, verbose_name='매매 유형'),
        ),
    ]
