# Generated by Django 4.2.30 on 2026-09-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0035_delete_intradayobservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(db_index=True, max_length=64, verbose_name='소유자 세션키')),
                ('exchange', models.CharField(default='upbit', max_length=20, verbose_name='거래소')),
                ('ticker', models.CharField(db_index=True, max_length=50, verbose_name='티커')),
                ('name', models.CharField(max_length=100, verbose_name='종목명')),
                ('memo', models.CharField(blank=True, default='', max_length=200, verbose_name='메모')),
                ('target_price', models.FloatField(blank=True, null=True, verbose_name='목표가')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['owner_key', 'exchange'], name='screener_fa_owner_k_a3e013_idx'), models.Index(fields=['owner_key', 'ticker'], name='screener_fa_owner_k_4de1ef_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('owner_key', 'exchange', 'ticker'), name='unique_owner_exchange_ticker_favorite'),
        ),
    ]
