# Generated by Django 4.2.30 on 2026-09-22 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screener', '0036_favorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='관리자 승인 여부')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인 일시')),
                ('approved_by', models.CharField(blank=True, default='', max_length=150, verbose_name='승인자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
